#!/bin/bash

# to enable this you must set the PROMPT_COMMAND=<path to this script> variable
# | green  user@host  | white     :| blue      path | white      $
# \[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$

# Black        0;30     
# Dark Gray     1;30
# Red          0;31     Light Red     1;31
# Green        0;32     Light Green   1;32
# Brown/Orange 0;33     Yellow        1;33
# Blue         0;34     Light Blue    1;34
# Purple       0;35    
# Light Purple  1;35
# Cyan         0;36    
# Light Cyan    1;36
# Light Gray   0;37     
# White         1;37

GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

inspect(){
  path=$(pwd)
  # look if u are at mounted folder in taxi_build
  remote="taxi_build"
  if [[ $path == *$remote* ]]
  then
    location='taxi_build'
  else
    location='local'
  fi
  # look for a repository
  url=$(git config --get remote.origin.url)'@'
  # if in repo or at taxi build:
  if [[ "$url" != '@' ]] || [[ $location == 'taxi_build' ]]
  then
    # inform the user
    printf $GREEN$url$RED$location'\n'
  fi

  # try to imbed the information into the prompt
  # that does not work, because the PS1 variable is not
  # exported properly with export PS1 for some reason
  export PS1=${PS1/\h/$msg}
}

inspect
